#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/docker_user
- name: Add user to docker group
  user:
    name: ducle
    groups: docker
    append: yes

- name: Enable Docker service
  systemd:
    name: docker
    enabled: yes
    state: started

