services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    restart: always
    depends_on:
      - ugc-ui
      - ugc-api
      - ugc-admin-api
      - ugc-admin
    networks:
      - app-network

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-ugcDEV@2026}
    networks:
      - app-network

  redis:
    image: redis
    container_name: redis
    restart: always
    networks:
      - app-network

  ugc-ui:
    image: ${REGISTRY:-docker.io}/${REGISTRY_USER:-ugc}/ugc-ui:${TAG:-latest}
    container_name: ugc.ui
    restart: always
    networks:
      - app-network

  ugc-api:
    image: lehongduc87/nginx-php:8.2
    container_name: ugc.api
    volumes:
      - ./ugc-api:/www
      - ./ugc-api/config/supervisor/workers.conf:/etc/supervisor/conf.d/workers.conf
    restart: always
    networks:
      - app-network

  ugc-admin-api:
    image: lehongduc87/nginx-php:8.2
    container_name: ugc.admin-api
    volumes:
      - ./ugc-admin-api:/www
    restart: always
    networks:
      - app-network

  ugc-admin:
    image: ${REGISTRY:-docker.io}/${REGISTRY_USER:-ugc}/ugc-admin:${TAG:-latest}
    container_name: ugc.admin
    restart: always
    networks:
      - app-network

networks:
  app-network:
    name: app-network
