services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    restart: always
    depends_on:
      - ugc-ui
      - ugc-api
      - ugc-admin-api
      - ugc-admin
    networks:
      - app-network

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ugcDEV@2026
    networks:
      - app-network

  redis:
    image: redis
    container_name: redis
    restart: always
    networks:
      - app-network

  ugc-ui:
    build:
      context: ./ugc-ui
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL:-https://www.ddev.online}
        - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL:-https://api.ddev.online/api/v1}
    container_name: ugc.ui
    restart: always
    networks:
      - app-network

  ugc-api:
    image: lehongduc87/nginx-php:8.2
    container_name: ugc.api
    volumes:
      - ./ugc-api:/www
      - ./ugc-api/config/supervisor/workers.conf:/etc/supervisor/conf.d/workers.conf
    restart: always
    networks:
      - app-network

  ugc-admin-api:
    image: lehongduc87/nginx-php:8.2
    container_name: ugc.admin-api
    volumes:
      - ./ugc-admin-api:/www
    restart: always
    networks:
      - app-network

  ugc-admin:
    build:
      context: ./ugc-admin
      dockerfile: Dockerfile
      args:
        - VUE_APP_BASE_API=${VUE_APP_BASE_API:-https://admin-api.ddev.online/admin-api}
        - VUE_APP_PUSHER_HOST=${VUE_APP_PUSHER_HOST:-ws.ddev.online}
        - VUE_APP_PUSHER_APP_KEY=${VUE_APP_PUSHER_APP_KEY:-wjvdnlaydeu1ogd6mov8}
        - VUE_APP_API_BASE_URL=${VUE_APP_API_BASE_URL:-https://api.ddev.online}
    container_name: ugc.admin
    restart: always
    networks:
      - app-network

networks:
  app-network:
    name: app-network
